task/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import *

router = DefaultRouter()
router.register(r'task-list', TaskAPI, basename='task-list')
router.register(r'task-photo', TaskPhotoAPI, basename='task-photo')

urlpatterns = [
    path('', index.as_view(), name='index'),
    
    path('add-task/', TaskCreateView.as_view(), name='add_task'),
    path('update-task/<int:pk>/', TaskUpdateView.as_view(), name='update_task'),
    path('delete/<int:pk>/', TaskDeleteView.as_view(), name='delete_task'),
    path('task-complete/<int:id>/', Task_Complete.as_view(), name='task_complete'),
    
    path('delete-image/<int:id>/', Delete_Image.as_view(), name='delete_image'),
    path('task/<int:id>/', Task_Details.as_view(), name='task_details'),
    
    path('api/', include(router.urls)),
]

task_management/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('task.urls')),
    path('', include('account.urls')),
    path('api-auth/', include('rest_framework.urls')),
    
    path('inbox/notifications/', include('notifications.urls', namespace='notifications')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

task/models.py
from django.db import models
from account.models import Custom_User

# Create your models here.
class Task(models.Model):
    PRIORITY = (
        ('Low', 'Low'),
        ('Medium', 'Medium'),
        ('High', 'High'),
    )
    title = models.CharField(max_length=300)
    description = models.TextField()
    due_date =models.DateTimeField()
    priority = models.CharField(choices=PRIORITY, default='Low', max_length=20)
    created_date = models.DateTimeField(auto_now_add=True, editable=False)
    updated_date = models.DateField(auto_now=True, editable=False)
    
    is_complete = models.BooleanField(default=False)
    task_project_link = models.URLField(blank=True, null=True)
    task_complete_user = models.ForeignKey(Custom_User, on_delete=models.DO_NOTHING, blank=True, null=True)
    task_complete_comment = models.TextField(blank=True, null=True)
    
    def __str__(self) -> str:
        return self.title


class Task_Photo(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE, related_name='task_photo', blank=True, null=True)
    image = models.ImageField(upload_to='task_photo/')
    
    def __str__(self) -> str:
        return self.image.name

    @property
    def image_url(self):
        return self.image.url

task/forms.py
from django import forms
from .models import Task

class Task_Form(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description', 'due_date', 'priority']
        widgets = {
            'title': forms.TextInput(attrs={
                'class': 'form-control', 'placeholder': 'Enter Task Title'
            }),
            'description': forms.Textarea(attrs={
                'class': 'form-control'
            }),
            'due_date': forms.DateTimeInput(attrs={
                'class': 'form-control', 'type': 'datetime-local'
            }),
            'priority': forms.Select(attrs={
                'class': 'form-control'
            }),
        }

task/views.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage, InvalidPage
from django.shortcuts import render, redirect, HttpResponse, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Case, When, IntegerField
from django.views import View, generic
from django.urls import reverse_lazy
from rest_framework import viewsets
from django.contrib import messages
from .forms import Task_Form
from .serializer import *
from .models import *
import os


class TaskAPI(viewsets.ModelViewSet):
    queryset = Task.objects.all()
    serializer_class = Task_Serializer

class TaskPhotoAPI(viewsets.ModelViewSet):
    queryset = Task_Photo.objects.all()
    serializer_class = TaskPhotoSerializer


class index(LoginRequiredMixin, generic.TemplateView):
    template_name = 'task/index.html'
    def get(self, request):
        context = {}
    
        filter = request.GET.get('filter')
        if filter:
            context['filter'] = filter
        search_value = request.GET.get('search_key')
        
        if search_value:
            task = Task.objects.filter(title__icontains=search_value)
        elif filter == 'id':
            task = Task.objects.all().order_by('id')
        
        elif filter == 'priority':
            task = Task.objects.all().order_by(
                Case(
                        When(priority='High', then=1),
                        When(priority='Medium', then=2),
                        When(priority='Low', then=3),
                        default=4,
                        output_field=IntegerField()
                    ),
            )
            
        elif filter == 'due_date':
            task = Task.objects.all().order_by('due_date')
        elif filter == 'created_date':
            task = Task.objects.all().order_by('-created_date')
        elif filter == 'complete':
            task = Task.objects.filter(is_complete=True)
        elif filter == 'incomplete':
            task = Task.objects.filter(is_complete=False)
        else:
            task = Task.objects.all().order_by('id')
        
        
        item_per_page = 5
        
        paginator = Paginator(task, item_per_page)
        page = request.GET.get('page')
        try:
            task_list = paginator.page(page)
        except PageNotAnInteger:
            task_list = paginator.page(1)
        except EmptyPage:
            task_list = paginator.page(1)
        except InvalidPage:
            task_list = paginator.page(1)
        
        context['task'] = task_list
        context['paginator'] = paginator
        return render(request, self.template_name, context)


class TaskCreateView(LoginRequiredMixin, generic.CreateView):
    model = Task
    form_class = Task_Form
    context_object_name = 'tasks'
    template_name = 'task/add_task.html'
    success_url = reverse_lazy('index')


class TaskUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Task
    form_class = Task_Form
    context_object_name = 'tasks'
    template_name = 'task/add_task.html'
    def get_success_url(self) -> str:
        return reverse_lazy('task_details', kwargs={'id': self.object.pk})



class Delete_Image(LoginRequiredMixin, View):
    def get(self, request, id):
        try:
            image = get_object_or_404(Task_Photo, id=id)
            os.remove(image.image.path)
            image.delete()
            return redirect(request.META['HTTP_REFERER'])
        except:
            return redirect(request.META['HTTP_REFERER'])


class Task_Details(LoginRequiredMixin, View):
    def get(self, request, id):
        task = get_object_or_404(Task, id=id)
        return render(request, 'task/task_details.html', {'task': task})
    
    def post(self, request, id):
        task_id = request.POST['task_id']
        task = get_object_or_404(Task, id=task_id)
        
        task_image = request.FILES.get('task_image')
        if not task_image:
            messages.warning(request, 'Image Must Be Set!')
            return redirect(request.META['HTTP_REFERER'])
        
        task_image_add = Task_Photo.objects.create(
            tast=task, image=task_image
        )
        return redirect(request.META['HTTP_REFERER'])

class Task_Complete(LoginRequiredMixin, View):
    def get(self, request, id):
        task = get_object_or_404(Task, id=id)
        return render(request, 'task/task_complete.html', {'task': task})
    
    def post(self, request, id):
        task = get_object_or_404(Task, id=id)
        task.task_project_link = request.POST['task_url']
        if request.POST['task_complete_comment']:
            task.task_complete_comment = request.POST['task_complete_comment']
        task.task_complete_user = request.user
        task.is_complete = True
        task.save()
        return redirect('task_details', id=task.id)

@login_required
def task_complete(request, pk):
    task = get_object_or_404(Task, id=pk)
    task.is_complete = True
    task.save()
    return redirect('task_details', id=pk)


class TaskDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Task
    template_name = 'task/task_delete_confirm.html'
    success_url = reverse_lazy('index')
    
    def delete(self, request, *args, **kwargs):
        try:
            task = self.get_object()
            task_image = task.task_photo.all()
            try:
                if task_image:
                    for i in task_image:
                        os.remove(i.image.path)
                        i.delete()
                task.delete()
                return redirect(reverse_lazy('index'))
            except:
                task.delete()
                return redirect(reverse_lazy('index'))
        except:
            return HttpResponse('Some Error')

templates/task/add_task.html
{% extends 'base.html' %}

{% block title %}
{% if form.instance.id %}
<title>Update Task | Task Manager</title>
{% else %}
<title>Add Task | Task Manager</title>
{% endif %}
{% endblock title %}


{% block body_content %}
<div style="width: 70%; margin: auto;">
    <form method="POST">
    {% csrf_token %}
        <div class="mb-3">
            <label for="InputTitle" class="form-label">Task Title</label>
            {{form.title}}
        </div>
        <div class="mb-3">
            <label for="InputDescription" class="form-label">Description</label>
            {{form.description}}
        </div>
        
        <div class="row">
            <div class="col-6">
                <div class="mb-3">
                    <label for="InputDescription" class="form-label">Priority</label>
                    {{form.priority}}
                </div>
            </div>
            <div class="col-6">
                <div class="mb-3">
                    <label for="InputDescription" class="form-label">Due Date</label>
                    {{form.due_date}}
                </div>
            </div>
        </div>
        {% if form.instance.id %}
        <button type="submit" class="btn btn-primary">Update Task</button>
        {% else %}
        <button type="submit" class="btn btn-primary">Add Task</button>
        {% endif %}
    </form>
</div>
{% endblock body_content %}

templates/task/index.html
{% extends 'base.html' %}

{% block title %}
<title>Home | Task Manager</title>
{% endblock title %}


{% block body_content %}

<style>
  .title_button {
    width: 100%;
    width: 100%;
    background-color: transparent;
    border: transparent;
    text-decoration: none;
    color: black;
  }
</style>

<table class="table table-striped">
  <thead>

    <tr>
      <th scope="col" style="width: 6%;">
        <a class="title_button" href="?filter=id">
          ID {% if filter == 'id' %}*{% endif %}
        </a>
      </th>

      <th scope="col">Title</th>

      <th scope="col">
        <a class="title_button" href="?filter=priority">
          Priority {% if filter == 'priority' %}*{% endif %}
        </a>
        <!-- <style>
          .dropdown-content {
            display: none;
            position: absolute;
            background-color: #f9f9f9;
            min-width: 160px;
            box-shadow: 0 8px 16px rgba(0, 0, 0, 0.2);
            z-index: 1;
          }

          .dropdown-content a {
            color: black;
            padding: 12px 16px;
            text-decoration: none;
            display: block;
          }

          .dropdown-content a:hover {
            background-color: #f1f1f1;
          }

          .dropdown:hover .dropdown-content {
            display: block;
          }
        </style> -->

        <!-- <div class="dropdown">
          <a href="" class="dropbtn">Priority {% if filter == 'priority' %}*{% endif %}</a>
          <div class="dropdown-content">
            <a href="?filter=priority">Option 1</a>
            <a href="#">Option 2</a>
            <a href="#">Option 3</a>
          </div>
        </div> -->

      </th>

      <th scope="col"><a class="title_button" href="?filter=due_date">
          Due Date {% if filter == 'due_date' %}*{% endif %}
        </a></th>
      <th scope="col"><a class="title_button" href="?filter=created_date">
          Created Date {% if filter == 'created_date' %}*{% endif %}
        </a></th>

      <th scope="col" style="width: 12%;">
        {% if filter == 'complete' or filter == 'incomplete' %}
        {% if filter == 'complete' %}
        <a class="title_button" href="?filter=incomplete">
          Complete {% if filter == 'complete' %}*{% endif %}
        </a>
        {% else %}
        <a class="title_button" href="?filter=complete">
          Inomplete {% if filter == 'incomplete' %}*{% endif %}
        </a>
        {% endif %}
        {% else %}
        <a class="title_button" href="?filter=complete">
          Status {% if filter == 'complete' %}*{% endif %}
        </a>
        {% endif %}
      </th>

      <th scope="col" style="width: 8%;">Action</th>
    </tr>

  </thead>
  <tbody>
    {% if task %}
    {% for task in task|dictsort:"priority" %}
    <tr>
      <th scope="row">{{task.id}}</th>
      <td>{{task.title|truncatewords:5|upper}}</td>
      <td>{{task.priority}}</td>
      <td>{{task.due_date|date:"SHORT_DATE_FORMAT"}}</td>
      <td>{{task.created_date|date:"D d M Y"}}</td>
      <td>
        {% if task.is_complete == True %}
        Complete
        {% else %}
        Incomplete
        {% endif %}
      </td>
      <td><a href="{% url 'task_details' task.id %}">View</a></td>
    </tr>
    {% endfor %}
    {% else %}
    <tr>
      <th colspan="7">No Task Found</th>
    </tr>
    {% endif %}
  </tbody>
</table>

<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    <li class="page-item {% if not task.has_previous %}disabled{% endif %}">
      <a class="page-link" {% if task.has_previous %}href="?page={{task.previous_page_number}}" {% endif %}
        tabindex="-1">Previous</a>
    </li>

    {% for page in paginator.page_range %}
    <li class="page-item {% if page == task.number %}active{% endif %}">
      <a class="page-link" href="?page={{page}}">{{page}}</a>
    </li>
    {% endfor %}

    <li class="page-item {% if not task.has_next %}disabled{% endif %}">
      <a class="page-link" {% if task.has_next %}href="?page={{task.next_page_number}}" {% endif %}>Next</a>
    </li>
  </ul>
</nav>

{% endblock body_content %}

templates/task/task_complete.html
{% extends 'base.html' %}

{% block title %}
<title>Task Completation | Task Manager</title>
{% endblock title %}


{% block body_content %}
<div style="width: 70%; margin: auto;">
    <form method="POST">
    {% csrf_token %}
        <div class="mb-3">
            <label for="InputTitle" class="form-label">Task Title</label>
            <input type="url" class="form-control" name="task_title" value="{{task.title}}" readonly disabled>
        </div>
        <hr>
        <div class="mb-3">
            <label for="InputTitle" class="form-label">Project URL Link</label>
            <input type="url" class="form-control" name="task_url" required>
        </div>
        <div class="mb-3">
            <label for="InputDescription" class="form-label">Comments</label>
            <textarea name="task_complete_comment" id="" rows="5" class="form-control"></textarea>
        </div>
        
        <button type="submit" class="btn btn-primary">Complete Task</button>
    </form>
</div>
{% endblock body_content %}

templates/task/task_delete.html
<!-- task_confirm_delete.html -->

<h2>Confirm Delete</h2>
<p>Are you sure you want to delete this task?</p>

<form method="post" action="">
    {% csrf_token %}
    <button type="submit">Yes, delete</button>
</form>

<a href="{% url 'index' %}">Cancel</a>

templates/task/task_delete_confirm.html
{% extends 'base.html' %}

{% block title %}
<title>Task Delete Confirmation | Task Manager</title>
{% endblock title %}


{% block body_content %}

<h2>Confirm Delete</h2>
<p>Are you sure you want to delete this task?</p>

<form method="post" action="">
    {% csrf_token %}
    <button type="submit">Yes, delete</button>
</form>

<a href="{% url 'index' %}">Cancel</a>

{% endblock body_content %}

templates/task/task_details.html
{% extends 'base.html' %}

{% block title %}
<title>Task Details | Task Manager</title>
{% endblock title %}


{% block body_content %}
<main>

    <section class="py-2 text-center container">
        <div class="row py-lg-2">
            <div class="col-lg-12 col-md-8 mx-auto">
                <h1 class="fw-light">{{task.title}}</h1>
                <p class="lead text-muted">{{task.description}}</p>
                <p>
                    <a class="btn btn-primary my-2">Priority: {{task.get_priority_display}}</a>
                    <a class="btn btn-secondary my-2">Status: {% if task.is_complete %}Complete{%else%}Incomplete{% endif %}</a>
                </p>
                <div class="row">
                    <div class="col-6">
                        <p class="lead text-muted">Task Create Date: {{task.created_date}}</p>
                    </div>
                    <div class="col-6">
                        <p class="lead text-muted">Task Due Date: {{task.due_date}}</p>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <div class="album py-2 bg-light">
        <div class="container">

            {% if request.user.user_type == 'Admin' or request.user.user_type == 'Employee' %}
            {% if task.is_complete == False %}
            <section class="text-center container">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row py-lg-2">
                        <div class="col-lg-12 col-md-8 mx-auto">
                            <div class="row" style="margin: auto; text-align: center;">
                                <div class="col-2">
                                    <input type="text" hidden value="{{task.id}}" name="task_id">
                                </div>
                                <div class="col-3">
                                    <input type="file" class="form-control" style="width: 100%;" accept="image"
                                        name="task_image">
                                </div>
                                <div class="col-5" style="text-align: left;">
                                    <button type="submit" class="form-control btn btn-primary" style="width: 40%;">Add
                                        Photo</button>
                                </div>
                                <div class="col-2">

                                </div>
                            </div>
                            {% if messages %}
                            {% for message in messages %}
                            {% if message == 'Image Must Be Set!' %}
                            <p><i>{{message}}</i></p>
                            {% endif %}
                            {% endfor %}
                            {% endif %}
                        </div>
                    </div>
                </form>
            </section>
            {% endif %}
            {% endif %}

            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-4 g-3">

                {% if task.task_photo.all %}
                {% for i in task.task_photo.all %}
                <div class="col">
                    <div class="card shadow-sm">

                        <img src="{{i.image.url}}" alt="" width="100%">

                        {% if task.is_complete == False %}
                        {% if request.user.user_type == 'Admin' or request.user.user_type == 'Employee' %}
                        <div class="card-body">
                            <p class="card-text"></p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a href="{% url 'delete_image' i.id %}"
                                        class="btn btn-sm btn-outline-secondary">Delete</a>
                                </div>
                                <!-- <small class="text-muted">9 دقائق</small> -->
                            </div>
                        </div>
                        {% endif %}
                        {% endif %}
                    </div>
                </div>
                {% endfor %}
                {% else %}
                <p>No photos for this task yet.</p>
                {% endif %}

            </div>
        </div>
    </div>


    <section class="text-center container">
        <div class="row py-lg-2">
            <div class="col-lg-12 col-md-8 mx-auto">
                <p>
                    {% if task.is_complete == False %}

                    {% if request.user.user_type == 'Admin' or request.user.user_type == 'Employee' %}
                    <a href="{% url 'update_task' task.id %}" class="btn btn-primary my-2">Edit Task</a>

                    {% if request.user.user_type == 'Admin' %}
                    <a href="{% url 'delete_task' task.id %}" class="btn btn-secondary my-2">
                        Delete Task
                    </a>
                    {% endif %}

                    {% endif %}

                    <a href="{% url 'task_complete' task.id %}" class="btn btn-secondary my-2">
                        Task Complete
                    </a>
                    {% else %}
                    <a class="btn btn-primary my-2">
                        Complete Successfully <i class="fa fa-check"></i>
                    </a>
                    {% endif %}
                </p>
            </div>
        </div>
    </section>

</main>







<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

<!-- jQuery and Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>



<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
    Launch demo modal
  </button>
  
  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          ...
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary">Save changes</button>
        </div>
      </div>
    </div>
  </div>

{% endblock body_content %}